// src/data/NutritionData.js
export const NutritionData = [
  {
    id: 1,
    name: "Omlet",
    calories: 200,
    protein: 12,
    carbs: 2,
    fat: 15,
    quantity: 1,
    mealType: "Breakfast",
  },
  {
    id: 2,
    name: "Grilled Chicken Breast",
    calories: 300,
    protein: 35,
    carbs: 0,
    fat: 7,
    quantity: 1,
    mealType: "Lunch",
  },
  {
    id: 3,
    name: "Steamed Rice",
    calories: 250,
    protein: 5,
    carbs: 50,
    fat: 2,
    quantity: 1,
    mealType: "Lunch",
  },
  {
    id: 4,
    name: "Boiled Eggs",
    calories: 150,
    protein: 13,
    carbs: 1,
    fat: 11,
    quantity: 2,
    mealType: "Snacks",
  },
  {
    id: 5,
    name: "Paneer (Cottage Cheese)",
    calories: 280,
    protein: 20,
    carbs: 8,
    fat: 18,
    quantity: 1,
    mealType: "Dinner",
  },
  {
    id: 6,
    name: "Oats with Milk",
    calories: 350,
    protein: 15,
    carbs: 55,
    fat: 8,
    quantity: 1,
    mealType: "Breakfast",
  },
  {
    id: 7,
    name: "Peanut Butter",
    calories: 190,
    protein: 8,
    carbs: 6,
    fat: 16,
    quantity: 1,
    mealType: "Snacks",
  },
  {
    id: 8,
    name: "Apple",
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
    quantity: 1,
    mealType: "Snacks",
  },
  {
    id: 9,
    name: "Banana",
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.3,
    quantity: 1,
    mealType: "Snacks",
  },
  {
    id: 10,
    name: "Salmon Fish",
    calories: 400,
    protein: 40,
    carbs: 0,
    fat: 25,
    quantity: 1,
    mealType: "Dinner",
  },
];

